// Code generated by MockGen. DO NOT EDIT.
// Source: app/handler/handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	types "message-system/app/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetSentMessages mocks base method.
func (m *MockService) GetSentMessages(ctx context.Context) ([]types.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSentMessages", ctx)
	ret0, _ := ret[0].([]types.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSentMessages indicates an expected call of GetSentMessages.
func (mr *MockServiceMockRecorder) GetSentMessages(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSentMessages", reflect.TypeOf((*MockService)(nil).GetSentMessages), ctx)
}

// StartSending mocks base method.
func (m *MockService) StartSending() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartSending")
}

// StartSending indicates an expected call of StartSending.
func (mr *MockServiceMockRecorder) StartSending() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSending", reflect.TypeOf((*MockService)(nil).StartSending))
}
